name: BuildAndTest_Segment2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:

  build:

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build Segment2_GUI\assistPurchaseGui.sln --configuration Release
    - name: Run unit tests
      run: dotnet test Segment2_GUI\assistPurchaseGui.sln --no-build --configuration Release

      
