name: Resharper_Code_Analysis_Segment1
 
on: 
    push:
        branches: [ main ]
 
jobs:
  resharper:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
           dotnet-version: 3.1.101
          
      - name: Install resharper
        run: dotnet tool install -g JetBrains.ReSharper.GlobalTools
        
      - name: Add package
        run: dotnet add Segment1_API/BackendTests/BackendTests.csproj package xunit --version 2.4.0
        
      - name: Run resharper inspection
        run: jb inspectcode Segment1_API/AssistPurchase.sln /output=insreport_segment1.xml
       
      - name: Run resharper duplicate code check
        run: jb dupfinder Segment1_API/AssistPurchase.sln /output=dupreport_segment1.xml
            
      - name: Check Reports
        run: powershell ./Segment1_API/resharper.ps1
